version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:

    working_directory: ~/repo

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - run: mvn clean test