version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build:

    working_directory: ~/repo

    docker: # run the steps with Docker
      - image: circleci/openjdk:11-jdk-browsers

    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew dependencies
      - run: ./gradlew test
      - run:
          name: Sonar analyze
          command: |
            ./gradlew sonarqube \
              -Dsonar.projectKey=lineball \
              -Dsonar.organization=lineball \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_LOGIN \
              -Dsonar.java.source=1.11
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    environment:
      HEROKU_APP: "lineball-server"
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master